"""
Django settings for shopdeck project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
X_FRAME_OPTIONS = "ALLOWALL"

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'shopdeckdb.apps.ShopdeckdbConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shopdeckdb.middleware.ShopMiddleware'
]

ROOT_URLCONF = 'shopdeck.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'webtemplates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shopdeck.wsgi.application'
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.django.project.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Server URLS (dont include a trailing slash at the end)
SOAP_URL = "ecs.c.shop.nintendowifi.net"
METADATA_API_URL = "ninja.ctr.shop.nintendo.net"

# TOS
TOS_ESHOP = "ENGLISH\n \nWelcome to Ghost eShop a 3DS Service \nResurrection ! :D \n \nGhost eShop is only available \nfor Nintendo 3DS family systems.\n \nWe're adding content regularly, so don't hesitate to take a look at what's new!\n \nA Nintendo Network ID is required if you want to download and install content \nfree of charge.\n \nIn order to support us and improve our \nservices, we have opened a page to \ncollect donations. \nhttps://ko-fi.com/ghostland \n \nThank you in advance for your support. \n \nCredit : \n2024 - Ghost eShop team \n(based on the Aftendo code) \n \nFRANCAIS\n \nBienvenue sur Ghost eShop, une \nrésurrection d'un service 3DS ! :D \n \nGhost eShop est uniquement disponible pour les consoles de la famille Nintendo 3DS. \n \nNous ajoutons régulièrement du \ncontenu, n'hésitez pas à jeter un coup \nd'oeil aux dernières nouveautés !\n \nUn identifiant Nintendo Network \nest nécessaire pour télécharger et \ninstaller gratuitement du contenu. \n \nAfin de nous soutenir et d'améliorer nos services, nous avons ouvert une page \npour collecter des dons. \nhttps://ko-fi.com/ghostland \n \nMerci d'avance pour le soutient.\n \nCredit : \n2024 - Ghost eShop team \n(basé sur le code de Aftendo)"

# Enable if maintenance is necessary
IN_MAINTENANCE = False

# Name of the web interface
WEBUI_NAME = "Ghost eShop"

#dont touch all of this
SESSION_COOKIE_NAME = "JSESSIONID"

STATIC_ROOT = "_static"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

AUTH_USER_MODEL = "shopdeckdb.User" 
